# Generated by Django 4.0.6 on 2022-07-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение локации'),
        ),
        migrations.AlterField(
            model_name='image',
            name='num',
            field=models.IntegerField(verbose_name='Порядковый номер изображения локации'),
        ),
    ]
