# Generated by Django 4.0.6 on 2022-07-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_image_alter_image_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='place',
            new_name='places',
        ),
    ]
