# Generated by Django 4.0.6 on 2022-07-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_rename_place_image_places'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['num'], 'verbose_name': 'Изображение локации', 'verbose_name_plural': 'Изображения локации'},
        ),
        migrations.AlterField(
            model_name='image',
            name='num',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер изображения локации'),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('title', 'lat', 'lng')},
        ),
    ]
